### ISSUE TITLE
Finish creating the survey

### ISSUE THREAD

**Issue by marcdotson** [andrewheiss/why-donors-donate#1]
@andrewheiss is going to provide a list of the questions we need to change in the survey. I'll work with my RA's (@meghop, @sabrinaweiler, @mitchellkimball, @maryrosemcqueen) to complete the draft on Qualtrics so we can start data collection.

**Comment by marcdotson** [comment]
Questions
- How does the consent work with screening questions? Note that you must be qualified to get paid?
- Do we need to define charity in Q2.5 or volunteering in Q2.8/Q2.9?
- Estimate on how much time it takes to complete the survey.
- Estimate on how much each person (who is qualified) will get paid.
- Q5.2 and Q5.3 might be redundant and seem to measure the same thing. Should we just keep Q5.3?

**Comment by marcdotson** [comment]
@meghop, @sabrinaweiler, @MitchellKimball, @maryrosemcqueen please submit a pull request with your changes to the survey to the master branch of marcdotson/why-donors-donate ASAP. I'd like to get this finished today.

**Comment by andrewheiss** [comment]
Oui oui!

**Comment by meghop** [comment]
@marcdotson, @andrewheiss Sorry for the delay! Edits have been officially been pushed to the master. Hopefully it worked...

**Comment by marcdotson** [comment]
Thanks. Let's make sure to make pull requests in the future. We'll talk about it more next week.

**Comment by marcdotson** [comment]
This might be another issue, but once we're all good on a finalized version of the survey to send to IRB, we'll need to code the survey again. I think it'll be best to do it from scratch given the changes and how easy it'll be to cut and paste from the markdown document. @meghop, let's create this using my account.

**Comment by marcdotson** [comment]
I confirmed with Centiment that we are ready for data collection as soon as the IRB approves the survey. A few details to record here from that conversation:

- Individuals representative of the general population who donate to charities. - Quote assumes at least 20% incidence rate from US general population.
- Up to 40 questions allowed.
- Up to an estimated 10 minutes to complete.
- 1,000 responses.

**Comment by marcdotson** [comment]
@meghop and anyone else who wants to help is going to transfer the [survey](https://github.com/andrewheiss/why-donors-donate/blob/master/analysis/survey/experiment.md) into Qualtrics.

Then test, test, test!

**Comment by meghop** [comment]
@marcdotson Survey is officially transferred to Qualtrics & being tested. Three quick questions. 

1. The skip logic wasn't included in the approved survey document, but should we terminate those that do give their consent in the first question? 
2. Should there be slashes between numbers (ex. how much did you donate to charity last year? \$1-\$49)
3. Can I publish the survey so it is easier to send out to try and "break"?

**Comment by meghop** [comment]
*** should we terminate those that do not give their consent

**Comment by marcdotson** [comment]
@meghop Yes, please terminate those who don't give their consent. Yes, slashes. Yes, publish the survey to test it, just don't distribute outside the group.

**Comment by marcdotson** [comment]
How has testing gone on the survey?

**Comment by marcdotson** [comment]
@meghop, @sabrinaweiler, @MitchellKimball, @maryrosemcqueen (if you're interested in completing this) here are some next steps:

- Confirm the estimated time-to-completion (10 minutes) is accurate.
- Make sure the survey (test [the survey here](https://byu.az1.qualtrics.com/jfe/form/SV_aXolqYvE0BXDRS5)) conforms as designed (see [the survey here](https://github.com/marcdotson/why-donors-donate/blob/pre-registration/analysis/survey/experiment.md)).
- @andrewheiss are we okay to split the *Organizational Practices* attribute into two binary attributes, *Financial Transparency* and *Accountability*?
- @MitchellKimball take a first look at the experimental design. Is it balanced across attribute levels? How many versions are there? If we need to, can we upload our own design?

**Comment by marcdotson** [comment]
![design_balance](https://user-images.githubusercontent.com/29615257/57170769-6a8ea500-6dcc-11e9-8142-7fe5c304c78e.png)

@MitchellKimball and I have checked the experimental design (in its current form). It's all balanced.

**Comment by andrewheiss** [comment]
Awesome. 

Yes, it's fine to split the organizational attributes into a binary (so it'd be transparency vs. accountability, right?)

**Comment by andrewheiss** [comment]
Ha, just kidding. Transparency yes/no + accountability yes/no.

**Comment by andrewheiss** [comment]
In that case, I propose we change the attributes to this kind of wording:

> *Financial transparency:* Organization discloses information regarding its donations and financial allocations in a timely and reliable manner.
> 
> *Accountability*: Organization undergoes a regular third-party audit to ensure that it is meeting its program goals and obligations.

I'll make a change to the static survey—the one on Qualtrics will need to be updated too.

**Comment by andrewheiss** [comment]
I added the new language in c810274 and 90239da

**Comment by marcdotson** [comment]
Thanks, @andrewheiss. That language looks good. I'll make the change to the survey and check the levels balance again.

**Comment by marcdotson** [comment]
Survey, including the design, updated. Balance, again, looks good.

![design_balance](https://user-images.githubusercontent.com/29615257/57247035-0ce09f80-6ffc-11e9-9384-095ee87bcd4b.png)

Now we (@MitchellKimball) just need to:

- Confirm the estimated time-to-completion (10 minutes) is accurate.
- Make sure the survey (test [the survey here](https://byu.az1.qualtrics.com/jfe/form/SV_aXolqYvE0BXDRS5)) conforms as designed (see [the survey here](https://github.com/andrewheiss/why-donors-donate/blob/master/analysis/survey/experiment.md)).

**Comment by embeukes** [comment]
@marcdotson Running through it the first time it took me 11.5 minutes. All the "termination" questions and forced responses seemed to work fine.

Here's my feedback:
1. In the intro page you say "By clicking "I agree" below...." but the button just has arrows and doesn't actually say "I agree". Little thing.
2. Q2.3 - do you want these to be randomized? Every time I clicked on them they were in the same order. (Also you could consider adding **"news app"** to the selections.)
3. I didn't see Q2.7, Q2.8, Q5.14 or Q2.11 so either you've got some funky skip logic going on or you decided to take those out?
4. Q5.10 allows you to select "other" and doesn't make you type anything into the box. Not sure if you wanted to force them to enter an option or not - just letting you know. (Same with Q5.16)
5. You need some kind of character verification on the zip code field. It let me enter "1" and "cats". :)
6. Also consider randomizing the answer order on Q5.3, Q5.10, and Q5.16.

Other than that it looks great!

**Comment by marcdotson** [comment]
Thanks, @embeukes!

**Comment by andrewheiss** [comment]
Remaining issues I found:

- [ ] Keep Q1.1 (consent text) and Q1.2 (consent question) on the same page (or put content of Q1.1 into the question for Q1.2 so that they can be on the same page, since each question right now is on its own page)
- [ ] I also didn't see Q2.7 or Q2.8 or Q2.11
- [ ] Participants go through 7 iterations of the conjoint questions, correct? In the static survey it says 12 times, but I can change it there
- [ ] With Q5.2, would it be possible to change the labels in the question to say "0 (extremely liberal)" and "7 (extremely conservative)"? (and do this for the other x-point scales like Q2.7, Q2.8, Q5.6, and Q5.11)
- [ ] Q5.10, Q5.12, and Q5.16 still don't require input in "Other"
- [ ] Where did we get the wording for prosocial views in Q5.11? I'm confused about equality vs. altruism (like, that's not a spectrum?). We should maybe consider rewording this one.
- [ ] Q2.6 and Q5.15 have slashes in front of all the dollar signs. This is a holdover from copying/pasting from Markdown where I had them escaped so they wouldn't turn into inline LaTeX
- [ ] Zip code still allows anything

**Comment by marcdotson** [comment]
@andrewheiss in addition to addressing the issues that have been raised (comments and questions below), I've also tried to clean up the survey layout and make the font sizes consistent. I've also moved the conjoint from a grid to cards, which will be easier to take on a mobile device. If you don't like it we can go back to the grid. Finally, I've included the attention check and made sure those who don't answer correctly are terminated, as we say in the consent form.

I think it's just the two of us who are available to edit. With your typography skillz and my copyediting skillz, we should be good. You can test [the survey here](https://byu.az1.qualtrics.com/jfe/form/SV_aXolqYvE0BXDRS5) and compare it to [the survey here](https://github.com/andrewheiss/why-donors-donate/blob/master/analysis/survey/experiment.md). Will you test it on both a computer and a mobile device?

> In the intro page you say "By clicking "I agree" below...." but the button just has arrows and doesn't actually say "I agree". Little thing.

I've changed this to "Yes."

> Q2.3 - do you want these to be randomized? Every time I clicked on them they were in the same order. (Also you could consider adding "news app" to the selections.)

I've randomized this order of these questions and added a "News app."

> I didn't see Q2.7, Q2.8, Q5.14 or Q2.11 so either you've got some funky skip logic going on or you decided to take those out?

These are now included.

> Q5.10 allows you to select "other" and doesn't make you type anything into the box. Not sure if you wanted to force them to enter an option or not - just letting you know. (Same with Q5.16)

We don't get anything out of forcing them to add anything to to the box, so I'd rather not force them.

> You need some kind of character verification on the zip code field. It let me enter "1" and "cats". :)

I can required they put in five characters, though they don't have to be numeric. I can look into this more if it's a serious concern.

> Also consider randomizing the answer order on Q5.3, Q5.10, and Q5.16.

I've randomized the order of Q5.3; for Q5.10 and Q5.16, are these just the standard order and we should leave them? We can randomize them (except for Other always being last).

> Keep Q1.1 (consent text) and Q1.2 (consent question) on the same page (or put content of Q1.1 into the question for Q1.2 so that they can be on the same page, since each question right now is on its own page)

Done.

>I also didn't see Q2.7 or Q2.8 or Q2.11

Fixed.

>Participants go through 7 iterations of the conjoint questions, correct? In the static survey it says 12 times, but I can change it there.

Should be 12, I've fixed it.

>With Q5.2, would it be possible to change the labels in the question to say "0 (extremely liberal)" and "7 (extremely conservative)"? (and do this for the other x-point scales like Q2.7, Q2.8, Q5.6, and Q5.11)

Added these anchors and changed them to actual 7-point rating scales (1 to 7).

>Q5.10, Q5.12, and Q5.16 still don't require input in "Other"

I think that's okay (see above).

>Where did we get the wording for prosocial views in Q5.11? I'm confused about equality vs. altruism (like, that's not a spectrum?). We should maybe consider rewording this one.

I'm not sure, to be honest. It must have been drawn from a source that was provided early on in the survey development. We can certainly change the wording or just remove it.

>Q2.6 and Q5.15 have slashes in front of all the dollar signs. This is a holdover from copying/pasting from Markdown where I had them escaped so they wouldn't turn into inline LaTeX

Fixed.

>Zip code still allows anything

See above.

**Comment by marcdotson** [comment]
@andrewheiss FYI, I'm making changes to [experiment.md](https://github.com/andrewheiss/why-donors-donate/blob/master/analysis/survey/experiment.md) as well. I'll make a PR once we've finalized things with those changes.

**Comment by marcdotson** [comment]
@andrewheiss changed the language for the 7-point rating scales from left-to-right to 1-to-7, since there is no left-to-right on the mobile version (i.e., it's vertical).

**Comment by marcdotson** [comment]
@andrewheiss the 7-point rating scale questions were still strange to me. I've rewritten them and made the scales vertical so it's easier to parse on mobile devices. If you aren't satisfied with this, I can return to the previous version, but the matrix setup isn't always mobile-friendly.

**Comment by andrewheiss** [comment]
@marcdotson Awesome, this looks great!

- You can randomize the order for religion and race
- I like the conjoint cards a lot.
- I've been hunting around online for where the prosocial question in Q5.11 came from and can't find anything. I've found lots of studies that use 10-15 questions to create indexes of prosociality and altruism, but no single questions. So maybe we should drop it? Unless Suparna knows where it came from…?
- Everything else is good

**Comment by marcdotson** [comment]
Final changes:

> You can randomize the order for religion and race

Done.

> I've been hunting around online for where the prosocial question in Q5.11 came from and can't find anything. I've found lots of studies that use 10-15 questions to create indexes of prosociality and altruism, but no single questions. So maybe we should drop it? Unless Suparna knows where it came from…?

Changed Q5.11 to "On a scale of strongly agree (1) to strongly disagree (7), rate your response to the following statement: People should be more charitable towards others in society."
