### ISSUE TITLE
Modify contributors

### ISSUE THREAD

**Issue by marcdotson** [andrewheiss/why-donors-donate#17]
Hey, @andrewheiss. Can you make the following changes to the contributors?

- Remove @maryrosemcqueen and @meghop.
- Add @sophie-cee.

Sophie is in the pre-PhD seminar I'm teaching this semester (the first half is Bayesian inference from _Statistical Rethinking_) and will be helping explore how to best visualize the results and draft some of the methods section.

**Comment by andrewheiss** [comment]
I just sent an invite to @sophie-cee!
