### ISSUE TITLE
Improve marginal posterior visualizations

### ISSUE THREAD

**Issue by marcdotson** [andrewheiss/why-donors-donate#18]
@sophie-cee you should have received an invite! Here's where we'll discuss and work on the visualization issue. We need better visualizations for the marginal posteriors. See the following code:

`03_analysis.Rmd > load-packages > plot-marginals`

Packages to get familiar with: bayesplot, tidybayes, ggridges.

**Comment by sophie-cee** [comment]
@marcdotson, encountered some issues loading packages. Could you take a look at the two errors in `03_analysis.Rmd > load-packages `?

**Comment by marcdotson** [comment]
Next steps from discussion today @sophie-cee:

- Filter down to visualize answers to specific questions/hypotheses in the paper.
- Look at adding color to the visualizations.
- Investigate adding the "credible interval" to the ridges plots?

**Comment by sophie-cee** [comment]
@marcdotson I've made a R Markdown to make it easier to visualize the main questions. 
`analysis > output > figures > marginal posterior visualizations > hypotheses.md`

What suggestions do you have for the markdown (besides the color) or other plots to look into?

**Comment by marcdotson** [comment]
Good idea, @sophie-cee. Follow the same structure as the other R Markdown documents (YAML, naming each code chunk, etc.)

**Comment by sophie-cee** [comment]
Next steps: 

* Put plots into the results section of `manuscript > manuscript.Rmd` . 
* Start writing interpretations for plots.

**Comment by marcdotson** [comment]
Finished (for Research Question 1) with PR #22.
