### ISSUE TITLE
Draft methods and results section

### ISSUE THREAD

**Issue by sophie-cee** [andrewheiss/why-donors-donate#21]
Use Beyond Limits of Survey Experiments to find further literature review.

Write a couple of paragraphs on the context of what's been done with conjoint analysis in the political and/or public policy field.

**Comment by marcdotson** [comment]
@andrewheiss we are trying to knit a draft of the manuscript. It produces an HTML file locally but nothing that we can commit or push to GitHub. Help?

Also, when are you presenting this next? We should have another meeting to figure out how to push through to that deadline and beyond.

**Comment by andrewheiss** [comment]
Just e-mailed!

**Comment by andrewheiss** [comment]
Oh also, don't worry about committing the HTML output (or PDF or whatever). The output is ephemeral and the result of the Markdown file, so it's not important—reknitting is trivial.

If *.html isn't in .gitignore already, you can add it there

**Comment by marcdotson** [comment]
I just wanted to read the output of the Markdown file instead of the Markdown file itself, be it HTML, GitHub Document -- whatever.

**Comment by marcdotson** [comment]
But maybe that doesn't matter. Let's talk about it in the call.

**Comment by marcdotson** [comment]
@sophie-cee here's the to-do list we just discussed:

1. For Q1 hypotheses, move back to `geom_halfeye()` so we can see the 95% credible intervals. Notify me and I'll make a PR for Andrew to use as he works on the results section draft.
2. Create a `methods-section` branch and keep working on that section, including the survey and an explanation of conjoint and its uses.
3. I'll find my code for creating a heat map for the covariate models for Q2. After finishing the results and methods section drafts, we can work on this bonus section for the presentation.

**Comment by marcdotson** [comment]
@andrewheiss how are things looking for the Nov. 15 submission deadline? Here's what's left on our to-do list. Tell me if you want help with something else:

- Create a `methods-section` branch and keep working on that section, including the survey and an explanation of conjoint and its uses.
- I'll find my code for creating a heat map for the covariate models for Q2. After finishing the results and methods section drafts, we can work on this bonus section for the presentation.

**Comment by andrewheiss** [comment]
Good good, we should be on track. I have a ton of uncommitted changes locally, and I made a new Rmd file for all the tables and figures that go into the paper 

Once I get more stuff polished, I'll commit and push. In the meantime, go ahead and branch and I'll bring in your changes later

<img width="372" alt="image" src="https://user-images.githubusercontent.com/73663/68711021-be8df980-0566-11ea-9db2-c84b45d869ea.png">

**Comment by sophie-cee** [comment]
@marcdotson, added the Methods section for you to review and revise.

**Comment by marcdotson** [comment]
Submitted PR #23.
