### ISSUE TITLE
Consider Oxfam scandal confounding

### ISSUE THREAD

**Issue by marcdotson** [andrewheiss/why-donors-donate#25]
> We speculate that Oxfam had the lowest baseline probability because of a lack of name recognition, but audience people think it might be related to the Oxfam scandal over the summer (https://www.thetimes.co.uk/article/oxfam-scandal-staff-still-offering-aid-for-sex-report-claims-pbx32xctw), but I kind of doubt that because I didn’t really hear about that over the summer and I, like, study this stuff, so who knows. They want us to check the timing of the survey to see if it aligns with the anti-Oxfam news cycle.

**Comment by marcdotson** [comment]
@sophie-cee just respond to the issue here and we'll move it into the manuscript once Andrew updates the repo.

**Comment by sophie-cee** [comment]
@marcdotson 
February 2018: 2011 Haiti scandal came out in the news 
May 14, 2019: "Oxfam fires 43 Staff following abuse investigations" - _CivilSociety_
May 29, 2019 - June 4, 2019: Survey data was collected
June 11, 2019: "Oxfam failed to report child abuse claims in Haiti, inquiry finds" - _The Gaurdian_

The bulk of the Oxfam scandal happened in 2018, but there are still occasional news reminders that may have kept it in low regard in people's minds.

See link below for a timeline:
https://www.civilsociety.co.uk/voices/timeline-of-the-oxfam-sexual-misconduct-scandal.html

**Comment by marcdotson** [comment]
@andrewheiss does that answer the concern about Oxfam being unduly impacted by the scandal news hitting? It's right in the middle, but it looks like the details of what they failed to report came out after the survey was finished.

Also, this was the US, and you nor I heard about it, so... *shrug*

**Comment by marcdotson** [comment]
Seems like this is a done deal:

`For instance, in February 2018, news broke about sexual abuse and misconduct at Oxfam and several other well known organizations, including Amnesty International and Save the Children. This potentially strengthened a narrative that the nonprofit sector suffers from governance failures (Phillips 2019). As such, it could be argued that respondents may be less likely to select Oxfam or Amnesty because of these scandals.
However, we remain doubtful that the above news would impact our U.S. respondents’ beliefs about these four organizations, as evidence about the effect of these scandals is mixed. Using data from Twitter, Scurlock, Dolsak, and Prakash (2020) find that while Oxfam’s reputation suffered for at least six months after the scandal (but has since recovered), other NGOs facing scandals, such as Save the Children, were able to recover more quickly. More broadly, the effect of scandals was mixed—while reputational damage can lead to decline in donations and grants, organizations can become more resilient and durable after a public relations recovery.
Additionally, we remain skeptical that this scandal affected U.S. donors, given Oxfam is based in the UK and lack of awareness about INGOs is well-documented (CITE).`
