### ISSUE TITLE
Changing of the guard (i.e., RAs)

### ISSUE THREAD

**Issue by marcdotson** [andrewheiss/why-donors-donate#29]
@andrewheiss we have some RAs to swap out/in.

- We can remove @Dperezc and @jeffgallini from the project.
- Add @evanwride and @z-wix.

**Comment by andrewheiss** [comment]
✅

**Comment by marcdotson** [comment]
Sorry, @andrewheiss, can you invite @evanwride again as a collaborator?

We can also remove @sophie-cee @Dperezc and @jeffgallini from the project.
