### ISSUE TITLE
Shiny/Flexdashboard Walkthrough

### ISSUE THREAD

**Issue by evanwride** [andrewheiss/why-donors-donate#30]
Here is the draft so far of the shiny/flexdashboard walkthrough. I got the shiny walkthrough to work, but for some reason the layout of the flexdashboard wasn't working. I got it to work in my own personal repository, but couldn't figure out the problem when running it through why-donors-donate.

Either way, the code is correct and the information is there to explain how to use both of these dashboards.

Shiny: https://github.com/andrewheiss/why-donors-donate/blob/market-simulator/analysis/shiny_walkthrough.Rmdj

Flexdashboard: https://github.com/andrewheiss/why-donors-donate/blob/market-simulator/analysis/flexdashboard_walkthrough.Rmd

@marcdotson @z-wix

**Comment by marcdotson** [comment]
Thanks, @evanwride. Moved to Issue #24 Create market simulator.
