### ISSUE TITLE
Export stuff from simulator

### ISSUE THREAD

**Issue by andrewheiss** [andrewheiss/why-donors-donate#31]
For the sake of reproducibility, it might be helpful if there were a way to export runs from the simulator (or include a `<code>`-delineated section on the flexdashboard page?). Perhaps some sort of plain text output like [CSVY](https://csvy.org/)?:

```
---
name: Simulation results
parameters:
  persona1:
    name: Persona 1
    follow_national_news: Something
    travel_to_developing_country: Something
  persona2:
    name: Persona 2
    etc.
---
market_share,organization,persona
16,"Organization 1", "Persona 1"
25,"Organization 1", "Persona 2"
48,"Organization 1", "Persona 3",
etc
```

**Comment by marcdotson** [comment]
This is a good idea. @z-wix let's look into it.

**Comment by marcdotson** [comment]
Let's have this be a separate branch once we have the simulator up and running in `master`. I was looking at a few things after our discussion today, @z-wix:

- Inputs. It may need to be part of the YAML, like Andrew outlines above, but if we can just input a CSV like we currently have that might be easier. What we need to test is whether or not we can reference a CSV as part of the input functions or if it has to be parameterized in the YAML.
- Output. I've seen a number of output options associated with rendered tables using the `DT` package. I supposed we can have a configuration output tab that renders the tables and gives an option to download as a CSV (assuming that can be then be used as an input).

**Comment by z-wix** [comment]
@marcdotson there is a fileInput() function with Flexdashboard that will allow you to import a file and then using that file_id we should be able to use it to populate the default selections for organizations and personas. I am still looking into a way to be able to output the renderTable of the market shares

**Comment by marcdotson** [comment]
@z-wix, perfect! And it's not the market shares we'll need to output -- it's a table of all of the organization configurations or persona configurations that can then then be used with `fileInput()` or whatever we use.

Now that `market-simulator` is merged, I'm creating a new branch, `configurations` to build out the import/export functionality.

**Comment by marcdotson** [comment]
@z-wix I've created an Export tab after all the other configurations in the `configurations` branch. We can render what the output will be from the simulator, and while I don't follow all of the UI requirements, it appears that [this page has what we need](https://mastering-shiny.org/action-transfer.html#download) to figure out how to first export the configuration tables and then we can figure out how to upload and reference the uploaded file inputs.

**Comment by z-wix** [comment]
@marcdotson I added a downloadButtons for those render tables in the Export tab. I also fileInputs at the top of the simulator, however, they are not yet connected to the reactive values to influence the data. Because the selectInputs need a character string, I think there is a way to have the number reflect the character string (e.g selected =c("1" = "Always")). So I will be looking into that more.

**Comment by marcdotson** [comment]
Some next steps from our meeting:

- Reference the imported configuration data for organization and persona defaults with *very careful* indexing.
- Create conditional argument to update the configuration data if new data is imported (maybe the apply button).
- Test by modifying configurations, exporting, importing, and double checking with the Excel simulator.

**Comment by z-wix** [comment]
@marcdotson The simulator can now be tested to make sure it checks with the Excel. The only thing that I am working on right now is that when you upload a new file, you have to reopen the tabs with the inputs that changed. So I am looking for a way that it will automatically update the inputs, perhaps with an actionButton.

**Comment by marcdotson** [comment]
@z-wix I think what we're looking for is the `req()` function (see [Mastering Shiny](https://mastering-shiny.org/action-transfer.html)). I'm not 100% on how to implement this, but it might require that we start with *no* default config, which is fine.

Take a look and let me know.

**Comment by z-wix** [comment]
@marcdotson Perfect, I am looking into it.

**Comment by marcdotson** [comment]
@z-wix any other changes to the market simulator I should know about before launching into testing after Thanksgiving?

**Comment by marcdotson** [comment]
Nice work, @z-wix. I cleaned up some comments while testing and changed the code and file names for defaults to `org_data_default.csv` and `per_data_default.csv`, respectively. PR #33 submitted and I'm closing this issue. If there are any other things to discuss about this issue, let's continue with comments in the PR.
