### ISSUE TITLE
Answer hypotheses using contrasts

### ISSUE THREAD

**Issue by marcdotson** [andrewheiss/why-donors-donate#35]
Follow-up with preregistration hypothesis tests and produce contrasts to answer each of them on the `contrasts` branch. Consider the need for ROPE bounds around zero in connection with contrasts.

Bonus work for me:

- Figure out how to access posterior draws from external to the repo.
- Confirm the market simulator is working as intended after the merge.
- Add unnecessary .rds files to the .gitignore.

**Comment by wtrumanrose** [comment]
hi @marcdotson

**Comment by wtrumanrose** [comment]
@marcdotson I have contrasts for marginal posterior intercepts by organization done, thought I'm not sure if I did it quite correctly. When do you want to meet? If it works for you, I can stop by right after the Pre-PhD seminar (it ends at 1:45pm). Just let me know!

**Comment by wtrumanrose** [comment]
@marcdotson I was kind of able to figure out the PAT--all I did was use it for when the password prompt came up. I'll keep working to figure out how to cache it, but I can at least push things now.

**Comment by marcdotson** [comment]
@wtrumanrose it worked! Let me clean it up and I'll get back to you on subsequent contrasts.

**Comment by marcdotson** [comment]
@wtrumanrose I cleaned up the code a bit. Take a look and compare how the new `contrasts_hypothesis01.png` in analysis > output > figures contains the same information as in `marginal-posteriors_intercept.png`, but answers the question more directly.

Let me set up the code for contrasts with the reference level and then you can produce the remaining contrasts, including quoting the pre-registration and providing an answer.

**Comment by wtrumanrose** [comment]
@marcdotson I checked out the code; I think I'm getting a good grasp on how to be consistent with the rest of the code. In the meantime, do you want me to start doing the contrasts related to the interaction effects (e.g., Hypothesis 2b)?

**Comment by marcdotson** [comment]
@wtrumanrose not yet, but you can replicate the contrasts for Hypothesis 1a for Hypothesis 2a, Hypothesis 3a, etc. It probably doesn't matter about the reference level, just read the current marginal posteriors as a contrast with that reference level set to the fixed value of zero. I'm going to try some recoding to see if that changes anything.

**Comment by wtrumanrose** [comment]
@marcdotson I took care of the remaining plots, I had a bit of trouble with the market simulator though. The market share between organizations wouldn't change when I changed government relationship. I'll keep messing with it to see if I can figure it out.

**Comment by marcdotson** [comment]
@wtrumanrose cool. Remember, you'll have to re-configure the compute sheet once taking out the personas and just working with the intercept gammas.

**Comment by wtrumanrose** [comment]
@marcdotson Hey Marc, I'm on the last few hypotheses--take a look and tell me what you think. The multi-interaction questions have me through a bit of a loop. The exact wording isn't final either, so I still have some work to do.

**Comment by wtrumanrose** [comment]
@marcdotson I cleaned up the old answers and got everything ready for the interactions. I made separate chunks for each sub-hypothesis contrast (e.g., 4a, 4b), but if you'd prefer to produce all the contrasts for a hypothesis in one chunk, I can alter it. I commented out the code for the interaction contrasts for the time being as well.

**Comment by marcdotson** [comment]
@wtrumanrose that sounds fine. I'm just wrestling with RStan to get the model with the interactions running.

**Comment by wtrumanrose** [comment]
@marcdotson gotcha, if the model takes awhile to run I'm happy to volunteer my computer for some iterations.

**Comment by marcdotson** [comment]
Okay @wtrumanrose I have an initial model run complete including interactions to answer Hypothesis 2b. It's currently saved under `../posterior_draws/interactions_2b.rds`. I have what will (hopefully) be the complete interactions model running now. Regardless, you can get started with the necessary contrasts using these interactions.

Here's what Hypothesis 2b includes:

```
# Hypothesis 2b.
amnesty_criticized = org1 * gov_rel2,
greenpeace_criticized = org2 * gov_rel2,
oxfam_criticized = org3 * gov_rel2,
redcross_criticized = org4 * gov_rel2,
amnesty_crackdown = org1 * gov_rel3,
greenpeace_crackdown = org2 * gov_rel3,
oxfam_crackdown = org3 * gov_rel3,
redcross_crackdown = org4 * gov_rel3
```

**Comment by wtrumanrose** [comment]
@marcdotson I finished the contrast plots for 2b, but am having a bit of a difficult time answering the actual hypothesis. For every contrast except for oxfam_amnesty_criticized, 0 is within the confidence(?) interval. Let me know what you think.

**Comment by marcdotson** [comment]
@wtrumanrose with the posterior draws I shared in the Drive folder, you should be able to produce a draft answer to all of the hypotheses. It won't be pretty though, I'm working on some options that I discussed with Andrew today.

**Comment by wtrumanrose** [comment]
@marcdotson Got it, I'll start working on them tonight. When do you need them by?

**Comment by marcdotson** [comment]
@wtrumanrose let's finish that by Friday.

**Comment by wtrumanrose** [comment]
@marcdotson It will be done, will we be meeting with Jeff et al this Friday as well?

**Comment by marcdotson** [comment]
@wtrumanrose yes!

**Comment by wtrumanrose** [comment]
@marcdotson hey Marc, I'm on track to finish everything by tomorrow, I've found something weird though--the posterior interactions for crackdown_wealthydonors and crackdown_grants have a much larger interval than their criticized counterparts. I'll push what I have so far in a minute so you can see.

**Comment by wtrumanrose** [comment]
@marcdotson Everything should be squared away with the contrast code, if there are any issues I missed let me know and I will fix it pronto.

**Comment by marcdotson** [comment]
@wtrumanrose I've uploaded posterior draws for each model that includes each subset of interactions. It's probably not going to give you something different, but the posterior intervals are more manageable on average. Go ahead and implement that and produce the necessary contrasts. I'm back to the drawing board for thinking about how we might be able to use the market simulator to answer these conditional hypotheses.

**Comment by marcdotson** [comment]
@wtrumanrose one thing to try with the contrasts using the interactions from each of the models covering each subset of intercepts (see the posterior draws folder in the shared Drive folder): We need to be contrasting the main effects + interactions, not just the interactions themselves. A comparison of what we have and the contrast of the main effects + interactions might be informative in our discussion of what little movement there is, especially if we have to go back to designing a study that can handle interactions.

**Comment by wtrumanrose** [comment]
@marcdotson okay sweet, I've been thinking about this quite a bit and was going to send you an email. I had a few questions/thoughts:

First, could the coding of the variables affect the interactions at all? In the model, we have some categorical variables which are dummy coded, and some which aren't. Does dummy coding change the scale of the gammas? For example, if Red Cross had a gamma of 1 and Amnesty had a gamma of 0.5, is the 0.5 difference between them on the same scale as a 0.5 difference between Emergency response (which is the reference group for issue area) and -0.5 gamma for Refugee relief? Intuitively, I would imagine they are the same, but it's something that crossed my mind.

Second, and this may be what you're talking about--some of the hypotheses are combinations of others. For example, 4b and 5b combine to make 5c. Wouldn't this mean that, if we answer 4b and 5b, we have an answer to 5c as well? Or do interaction effects mean that this isn't necessarily true? 

Third, the study design per https://stats.andrewheiss.com/why-donors-donate/experiment.html is a little confusing. It states "We present respondents with 4 hypothetical organizations that have 4 randomly assigned features. Respondents will be shown 12 sets of hypothetical organizations. This partial fractional factorial design results in 288 (4 × 4 × 2 × 3 × 3) possible combinations of organization features..."--the chart above this blurb shows 3 hypothetical organizations with all 6 randomly assigned features. Wouldn't this also result in the full 576 possible combinations? Also, if we do have to go back and redesign the study, would asking subjects to rank the organizations bias the results as opposed to asking them to choose one or none? If it doesn't significantly alter the results or the interpretation of the results, it could be a way to get more information per subject.

I apologize if some of my questions aren't very clear--I've spent the past 2 hours writing this trying to think through it and word it so it makes sense. I'll get to work on the main effect+interaction contrasts!

**Comment by marcdotson** [comment]
> @marcdotson okay sweet, I've been thinking about this quite a bit and was going to send you an email. I had a few questions/thoughts:
> 
> First, could the coding of the variables affect the interactions at all? In the model, we have some categorical variables which are dummy coded, and some which aren't. Does dummy coding change the scale of the gammas? For example, if Red Cross had a gamma of 1 and Amnesty had a gamma of 0.5, is the 0.5 difference between them on the same scale as a 0.5 difference between Emergency response (which is the reference group for issue area) and -0.5 gamma for Refugee relief? Intuitively, I would imagine they are the same, but it's something that crossed my mind.

@wtrumanrose the coding changes things in terms of interpretation. However, when it comes to contrasts, we arrive at the same contrast despite how we've coded the discrete variables.

> Second, and this may be what you're talking about--some of the hypotheses are combinations of others. For example, 4b and 5b combine to make 5c. Wouldn't this mean that, if we answer 4b and 5b, we have an answer to 5c as well? Or do interaction effects mean that this isn't necessarily true?

Okay, so for 4b ("Donors will show increased willingness to donate to NGOs that are facing government crackdown and are funded primarily by numerous small private donors") we need to contrast government_crackdown + small_private_donors + government_crackdown * small_private_donors. I don't see this answering other hypotheses directly, although it's part of answering other hypotheses.

> Third, the study design per https://stats.andrewheiss.com/why-donors-donate/experiment.html is a little confusing. It states "We present respondents with 4 hypothetical organizations that have 4 randomly assigned features. Respondents will be shown 12 sets of hypothetical organizations. This partial fractional factorial design results in 288 (4 × 4 × 2 × 3 × 3) possible combinations of organization features..."--the chart above this blurb shows 3 hypothetical organizations with all 6 randomly assigned features. Wouldn't this also result in the full 576 possible combinations? Also, if we do have to go back and redesign the study, would asking subjects to rank the organizations bias the results as opposed to asking them to choose one or none? If it doesn't significantly alter the results or the interpretation of the results, it could be a way to get more information per subject.

I don't think we'll be doing another study. Not all possible combinations are present in the design -- we use what is called a fractional factorial design. If we did another study it would still be fractional factorial and we would likely use rating scales instead of choices.

> I apologize if some of my questions aren't very clear--I've spent the past 2 hours writing this trying to think through it and word it so it makes sense. I'll get to work on the main effect+interaction contrasts!

All good. I'll send an email to schedule a time to talk.

**Comment by wtrumanrose** [comment]
@marcdotson Hey Marc--I apologize I wasn't able to push the code yesterday, I was struggling a bit to think through how to do it. In the changes I've pushed, I made 2 versions of hypothesis 2b contrasts. The first one includes the main effects for both organizations and government relationship, the equation for the contrasts being:
((oxfam + oxfam_criticized) - (amnesty + amnesty_criticized) + criticized)

The alternate version, which produced result that can be interpreted as significant, was written as:
(oxfam + oxfam_criticized) - (amnesty + amnesty_criticized)
All I did was leave out the main effect for criticized (main effects were pulled from the draws.rds). Confirmation bias has me to believe that the alternate version is the proper way to show it, but I'm not entirely sure, so I included both to see what you think. Let me know which of them you want to do for the rest, or if there is a different way we should go about it. It didn't take me long at all to do once I figured it out, so I can have the code + hypothesis answers ready for Friday.

**Comment by marcdotson** [comment]
@wtrumanrose almost there. It should be (oxfam + criticized + oxfam_criticized) - (amnesty + criticized + amnesty_criticized). We need both main effects to be included, though it should look like your (oxfam + oxfam_criticized) - (amnesty + amnesty_criticized) since criticized will be differenced out.

I've cleaned it up a bit and posted changes. We can't use the `interactions.rds` alone since we need to use the separate interaction models, like `interactions_2b.rds` when evaluating Hypothesis 2b. I've tried to make that clear, starting in `crackdown-contrasts-b` by adding an import code specific for those draws, but I haven't revised your code with the separate tables to incorporate that change. Take a shot at the rest of them and we'll finalize it tomorrow.

EDIT: Except now all of the draws should be put in `data/raw_data/posterior_draws`. You'll need to make that change.

**Comment by marcdotson** [comment]
Okay, @andrewheiss, I may have goofed. I wanted to merge changes you made in `master` into `contrasts`, but when I resolved the merge conflicts it looks like it just went ahead and did the opposite as well and merged `contrasts` changes into `merge`, which is dumb. If you need to roll back whatever changes I just made to `master`, go ahead. Apologies.

**Comment by wtrumanrose** [comment]
@marcdotson Understood, I'll get everything in shape. Am I taking the posterior draws from the Drive and putting them in data/raw_data/posterior_draws for the pull request?

**Comment by marcdotson** [comment]
@wtrumanrose yeah, I think that's easiest to manage the reorganization. And then you'll need to update any import statements to that new file path, including all of the ones I added for hypotheses using interactions.

**Comment by wtrumanrose** [comment]
@marcdotson Copy that, I should be able to tackle all of that today--I'll update the issue later tonight with what I have done.

**Comment by wtrumanrose** [comment]
@marcdotson Alright, I have some good news and some bad news.

Bad news first--I was able to stick the interaction rds files into the posterior draws folder for raw data. However, when I try to import that data, R doesn't like that the file is that big, and won't read in a vector 16kb long (this is after wrapping it in read_rds; if I don't include that, it just provides the path to the file). I tried to use some code from the analysis file to pull the specific draws I need, but I'm having a difficult time getting it to work.

The good news is that I can still do most of the coding for producing the actual contrasts. Assuming the i's are all the same, I can set up the code so that all that will be left is figuring out the import code. Although I *might* be able to figure it out, it would probably take a good chunk of time, and I imagine you already know how to do it and can explain it easily. I'm not finished with the contrast code yet, but I'll have it ready tomorrow for sure.

**Comment by marcdotson** [comment]
@wtrumanrose okay, posterior_draws replaced. It was definitely model_runs that I added accidentally.

Tag me when your pass is done and I'll finish it up.

**Comment by wtrumanrose** [comment]
@marcdotson will do, we're not meeting at 4 right?

**Comment by marcdotson** [comment]
@wtrumanrose no need.

**Comment by wtrumanrose** [comment]
@marcdotson cool, also, could you reupload interactions_3b? my finger slipped and I hit remove instead of download, and it doesn't let me undo it for whatever reason. edit: sorry!

**Comment by marcdotson** [comment]
@wtrumanrose done.

**Comment by wtrumanrose** [comment]
@marcdotson awesome thank you Marc, a few things I wanted to ask you about:

First, should I reimport the draws for each contrast block, regardless of whether or not it has an interaction? For example, 5a, which doesn't have an interaction, would use draws from interactions_4c.rds. My solution would be to just import the intercept draws for the relevant contrasts and use those--let me know if you have other ideas.

Second, for hypotheses with more than 2 factors interacting, such as hypothesis 5c, should I include the lower order interaction terms as well? I think this was actually what I was trying to ask about a week ago with my question about 4b, 5b and 5c, I just didn't process it like this. Hypothesis 5c states "Donors will show increased willingness to donate to NGOs that are criticized by the government/under government crackdown when they are also financially transparent and are funded primarily by numerous small private donors". I'm not sure if the triple interaction already contains the lower order interactions, but if it doesn't, shouldn't the interactions be something like:
(fin_transparency + criticized + fin_transparency_criticized + fin_transparency_smalldonors + criticized_smalldonors + fin_transparency_smalldonors_criticized) - (fin_transparency + criticized + wealthy_donors + fin_transparency_criticized + fin_transparency_wealthydonors  + criticized_wealthydonors + fin_transparency_wealthydonors_criticized)

We have the criticized_wealthydonors interaction term from 4b and the fin_transparency_criticized term from 5b, though we lack fin_transparency_smalldonors/wealthydonors. Again, I'm not sure if the lower order interactions are contained within the higher order ones, but if that's the case then it shouldn't be a concern. I probably should've realized this when I put together the word document with all the interactions, so that's my bad.

Finally, I'm having some trouble with 4c--I think I may have gotten "many small private donors" and "few wealthy private donors" mixed up at some point. I think I know how to do the contrasts, I just wanted to give you a heads up about it when you look it over.

Sorry for the Great Wall of Text, if I knew I was this confused I might've asked to meet lol.

**Comment by wtrumanrose** [comment]
@marcdotson I'm wrapping up for today to work on another project due tonight, here's what I've done and plan to do:

-Interaction rds files are in the posterior draws folder, and are able to be imported now.
-All contrast code is functional, but the figures for hypotheses 4c, 5d and 5e aren't right and need to be looked at. I've tried a couple of things,  but don't have the time today to look into it further. It may very well be that those are the results we have; if that is the case, some adjustments will need to be made to the graphing code.
-Tomorrow, I'm going to try to standardize the coding of the factors and answer what hypotheses I can. Fortunately, the contrasts that are working provide pretty clear results, so it shouldn't be difficult.

**Comment by marcdotson** [comment]
> @marcdotson I'm wrapping up for today to work on another project due tonight, here's what I've done and plan to do:
>
> -Interaction rds files are in the posterior draws folder, and are able to be imported now.

@wtrumanrose just used the intercept-only model if no interaction terms are needed in the contrast.

> -All contrast code is functional, but the figures for hypotheses 4c, 5d and 5e aren't right and need to be looked at. I've tried a couple of things, but don't have the time today to look into it further. It may very well be that those are the results we have; if that is the case, some adjustments will need to be made to the graphing code.

Yes, we'll need all the lower-order interactions included in the contrast. We can mix and match across interaction models.

> -Tomorrow, I'm going to try to standardize the coding of the factors and answer what hypotheses I can. Fortunately, the contrasts that are working provide pretty clear results, so it shouldn't be difficult.

I see you've posted one change. Let me know once you're finished with your attempt tomorrow, hopefully early, so I can take my pass at it.

**Comment by wtrumanrose** [comment]
@marcdotson Hey Marc, just to keep you posted, I'm almost done adding the lower-order interactions I have (there are some we don't have draws for), as well as rewriting the conclusions. So far, I'm still having trouble with 4c, I'm about to do 5d so hopefully I can at least get those to work. I should have it pushed by 2, I'll let you know. Also, were you able to see all the changes I did yesterday? On my end it looks like I committed + pushed everything correctly, let me know if there are problems.

**Comment by wtrumanrose** [comment]
@marcdotson Apologies for not having the changes pushed yet, 5e has a ridiculous amount of lower-order interactions.

**Comment by wtrumanrose** [comment]
@marcdotson Despite my best efforts, 4c, 5d and 5e are still pretty bonkers. Fortunately, the other hypotheses had clean results, with only a few contrasts here and there containing 0. My only concern is that we lack lower-order interactions for a few contrasts, but ultimately it probably wouldn't change the results.

**Comment by marcdotson** [comment]
@wtrumanrose long story, but I'm on it. Thanks.

**Comment by wtrumanrose** [comment]
@marcdotson cool cool, I'll keep an eye on my email, but I probably won't be able to do much till next Tuesday. I have two scheduled finals, one Monday and the other Tuesday, so it'll basically be nonstop studying. After that, I'll only have one more final, so I can fit in some research work then.

**Comment by marcdotson** [comment]
PR #37 made. Closing this issue out.
