### ISSUE TITLE
Schedule summer meeting

### ISSUE THREAD

**Issue by marcdotson** [andrewheiss/why-donors-donate#6]
@meghop @maryrosemcqueen @sabrinaweiler @MitchellKimball if you're interested in helping see this through, what would be a good time for you to meet over the summer?

**Comment by MitchellKimball** [comment]
I thought we weren’t allowed to work?

**Comment by marcdotson** [comment]
You can work up to two weeks after graduation. There was also some interest in helping with the project without getting paid. If neither of those are of interest or apply to you, all good. :)

**Comment by MitchellKimball** [comment]
Got it. Interested in both

**Comment by marcdotson** [comment]
Cool. What would be a good time to meet over the summer?

**Comment by MitchellKimball** [comment]
After 5 everyday works for me!

**Comment by marcdotson** [comment]
Let's do 5:30 on Thursdays.

**Comment by MitchellKimball** [comment]
Are we starting today?

**Comment by marcdotson** [comment]
Yes, let's start today!
