### ISSUE TITLE
Details for the pre-registration

### ISSUE THREAD

**Issue by marcdotson** [andrewheiss/why-donors-donate#7]
- Reference justifying the sample size.
- Provide language around "significance" for part-worth estimates (e.g. using HPD for the marginal posteriors, measures of model fit).
- Explain the design creation and assignment to different versions of the design.

**Comment by marcdotson** [comment]
Reference previous pre-registration: [https://osf.io/dx973](https://osf.io/dx973)

**Comment by andrewheiss** [comment]
And here's a previous pre-registration for a conjoint hierarchical MNL model: <https://osf.io/u43yg>

**Comment by andrewheiss** [comment]
`preregistration.Rmd` is ready for you to edit and fill in: https://github.com/andrewheiss/why-donors-donate/blob/master/analysis/survey/preregistration.Rmd

**Comment by marcdotson** [comment]
Moved this all into the PR #8.
